name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image for Raspberry Pi (arm64)
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t portfolio:latest --load .

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Raspberry Pi to known_hosts
      run: ssh-keyscan 62.248.139.131 >> ~/.ssh/known_hosts

    - name: Push Docker image to Raspberry Pi
      run: |
        docker save portfolio:latest | bzip2 | ssh juhojarvi@62.248.139.131 'bunzip2 | docker load'

    - name: Stop and remove existing container
      run: ssh juhojarvi@62.248.139.131 'docker stop portfolio || true && docker rm portfolio || true'

    - name: Deploy Docker container on Raspberry Pi
      run: ssh juhojarvi@62.248.139.131 'docker run -d -p 3001:80 --name portfolio portfolio:latest'