name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Raspberry Pi to known_hosts
      run: ssh-keyscan 62.248.139.131 >> ~/.ssh/known_hosts

    - name: Copy files to Raspberry Pi
      run: scp -r ./dist/* juhojarvi@62.248.139.131:/tmp/portfolio/

    - name: Clean target directory
      run: ssh juhojarvi@62.248.139.131 'sudo rm -rf /www/portfolio/*'

    - name: Move files to target directory with sudo
      run: ssh juhojarvi@62.248.139.131 'sudo mv /tmp/portfolio/* /www/portfolio/'

    - name: Restart Nginx
      run: ssh juhojarvi@62.248.139.131 'sudo systemctl restart nginx'